#!/bin/bash
set -eo pipefail

usage () {
	cat <<-EOF
		Usage: $(basename $0) -u url [-n filename] [-d dest] [-x] [-c checksum] [-p program]

		Download, check and install a file from a URL using cURL.
		cURL will be installed from package repositories if absent.

		Options:
		  -u	URL of the file
		  -n	Name of the file once installed (default: same as source)
		  -d	Directory to move the file to (default: '/usr/local/bin')
		  -x	Make the file executable
		  -c	File checksum
		  -p	Program used for checking file checksum (default: 'sha1sum')
		  -h	Display this help and exit
	EOF
	exit 1
}

# set defaults
fileDest=/usr/local/bin
checksumProgram=sha1sum

# read flags
while getopts :u:n:d:xc:p:h opt; do
	case $opt in
	u)
		url="$OPTARG"
		;;
	n)
		fileName="$OPTARG"
		;;
	d)
		fileDest="$OPTARG"
		;;
	x)
		makeExec=true
		;;
	c)
		checksum="$OPTARG"
		;;
	p)
		checksumProgram="$OPTARG"
		;;
	h)
		usage
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		exit 1
		;;
	:)
		echo "Option -$OPTARG requires an argument" >&2
		exit 1
		;;
	esac
done

shift $(($OPTIND - 1))

if [ -z "${url:-}" ]; then
	echo "Option -u is required" >&2
	echo
	usage
fi

# install curl if required
which curl &>/dev/null && curlPresent=true
if [ -z "${curlPresent:-}" ]; then
	apt-get update -qq >/dev/null
	apt-get install -qq --no-install-recommends curl >/dev/null
fi

# set program name if unset
if [ -z "${fileName:-}" ]; then
	fileName=$(echo $url | awk -F "/" '{print $NF}' | awk -F "?" '{print $1}')
fi

# create tmpdir to download file
tmpdir=$(mktemp -d)
pushd "$tmpdir" >/dev/null

# fetch file passed as URL
curl -fsSL "$url" -o "$fileName"
if [ ! -z "${makeExec:-}" ]; then
	chmod +x "$fileName"
fi

# check checksum if passed as option
if [ ! -z "${checksum:-}" ]; then
	echo "$checksum  $fileName" | "$checksumProgram" -c -
fi

# install file to its final location and delete tmpdir
mkdir -p "$fileDest"
mv "$fileName" "$fileDest"
popd >/dev/null
rm -rf "$tmpdir"

# uninstall cURL if we installed it earlier
if [ -z "${curlPresent:-}" ]; then
	apt-get purge -qq curl >/dev/null
	apt-get autoremove -qq --purge >/dev/null
	rm -rf /var/lib/apt/lists/*
fi
